# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-13 10:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='scity',
            field=models.CharField(choices=[('Select', 'Select'), ('Bangalore', 'Bangalore'), ('Kolar', 'Kolar'), ('Mysore', 'Mysore'), ('Mandya', 'Mandya')], default='select', max_length=6),
        ),
    ]
