# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-13 12:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_student_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Unisex/Parody', 'Unisex/Parody')], default='', max_length=1),
        ),
    ]
