# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-19 04:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0008_auto_20190613_1301'),
    ]

    operations = [
        migrations.CreateModel(
            name='Revenue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MonthlyRevenue', models.CharField(max_length=50)),
                ('Month', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='scity',
            field=models.CharField(choices=[('Select', 'Select'), ('Bangalore', 'Bangalore'), ('Kolar', 'Kolar'), ('Mysore', 'Mysore'), ('Mandya', 'Mandya')], default='select', max_length=20),
        ),
    ]
