# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-19 12:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0012_auto_20190619_1210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='DOB',
        ),
    ]
