# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-19 12:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0014_student_dob'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='DOB',
            new_name='sdob',
        ),
    ]
