# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-20 04:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0015_auto_20190619_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='lastname',
            field=models.CharField(max_length=20, null=True, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='student',
            name='sname',
            field=models.CharField(max_length=100, verbose_name='First Name'),
        ),
    ]
