# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-20 06:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0016_auto_20190620_0420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('U', 'Unisex/Parody')], default='', max_length=1, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='student',
            name='scity',
            field=models.CharField(choices=[('Select', 'Select'), ('Bangalore', 'Bangalore'), ('Kolar', 'Kolar'), ('Mysore', 'Mysore'), ('Mandya', 'Mandya')], default='select', max_length=20, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='student',
            name='scontact',
            field=models.CharField(max_length=15, verbose_name='Contact'),
        ),
        migrations.AlterField(
            model_name='student',
            name='sdob',
            field=models.DateField(null=True, verbose_name='DOB'),
        ),
        migrations.AlterField(
            model_name='student',
            name='semail',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
    ]
