# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-21 04:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0021_auto_20190621_0428'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='degreecollege',
            new_name='Degree_College',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='Diplomastream',
            new_name='Diploma_Stream',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='degreestream',
            new_name='degree_Stream',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='masterdegree',
            new_name='master_Degree',
        ),
    ]
