# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-21 04:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0022_auto_20190621_0434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='scity',
            field=models.CharField(default='', max_length=20, verbose_name='City'),
        ),
    ]
