# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-21 05:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0024_auto_20190621_0550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='pincode',
            field=models.IntegerField(null=True, verbose_name='Pincode'),
        ),
    ]
