# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-21 06:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0025_auto_20190621_0556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('U', 'Unisex/Parody')], default='', max_length=15, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='student',
            name='masterdegreeoption',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='', max_length=10, verbose_name='Have you done Master Degree?'),
        ),
    ]
